baseURL = "https://github.com/Divya-1200/mynotes/"
languageCode = "en-us"
title = "Divya"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]